sonar.projectKey=vil4max_ios-vacancy-radar
sonar.organization=vil4max
sonar.sources=.
sonar.tests=tests
sonar.exclusions=**/.build/**,**/database/*.json,**/database/*.db,tests/**
sonar.python.version=3.12
